[package]
name = "sparkle"
version = "0.1.0"
authors = ["Jack Lewis <jack@jacklew.is>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "sparkle"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = []

experimental = ["esp-idf-svc/experimental"]

[dependencies]
anyhow = "1.0.98"
byteorder = "1.5.0"
embedded-graphics = "0.8"
esp32-nimble = "0.11.1"
esp-idf-hal = "0.45.2"
esp-idf-sys = { version = "0.36.1", features = ["binstart"] }
esp-idf-svc = { version = "0.51", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
display-interface = "0.5"
display-interface-spi = "0.5"
log = "0.4"
ssd1306 = "0.10"
uuid = "1.16.0"
zerocopy = { version = "0.8", default-features = false, features = ["derive"] }

[build-dependencies]
embuild = "0.33"
