[build]
rustflags = [
  "-C", "link-arg=-Tdefmt.x",
]

target = "xtensa-esp32-none-elf"

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --log-format defmt --port /dev/cu.usbserial-0001"

[unstable]
build-std = ["alloc", "core"]

[env]
MCU = "esp32"

DEFMT_LOG = "trace"
DEFMT_TIME_FORMAT = "{=u64:us}"

ESP_LOG = "INFO"
