[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOG="INFO"

[build]
rustflags = [
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Tdefmt.x",

]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core", "alloc"]
